### ISSUE TITLE
Github Actions Golangci-lint is not working correctly

### ISSUE THREAD

**Issue by zyiou** [vmware/go-ipfix#119]
**Describe the bug**
Golangci-lint is passed automatically even though there is error in `make golangci-lint`.

**To Reproduce**
run `make golangci-lint` locally with some error logs. when pushing the code, the workflow will pass.
Here is an [example](https://github.com/vmware/go-ipfix/runs/1561102825?check_suite_focus=true) run.

**Expected behavior**
workflow should not pass when there are errors in golangci-lint and marked workflow as failed.

**Actual Behavior**
Golangci-lint workflow passed.

**Versions**
master branch

**Additional context**

**Comment by srikartati** [comment]
Issue is fixed in the linked PR.
