### ISSUE TITLE
CollectingProcess TCP handler memory leak

### ISSUE THREAD

**Issue by sheacloud** [vmware/go-ipfix#138]
**Describe the bug**
The TCP client handler goroutines under the collector process live forever, waiting on a channel, even after the TCP connection has been closed. 
https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L98 waits for a value to be passed to the clients error channel, but from what I can see, nothing ever gets written to that channel unless you explicitly call the CollectingProcess.closeAllClients. This results in [this goroutine](https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L51) living forever, building up memory within the application.

**To Reproduce**

1. Create a collecting process based on a TCP address (the code at https://github.com/vmware/go-ipfix/blob/master/cmd/collector/collector.go produces the issue when using TCP)
2. (To better see the issue) add profiling to the program via [pprof](https://golang.org/pkg/net/http/pprof/)
2. Create multiple TCP connections to the process
3. View the pprof goroutine profile, which shows current goroutines in the application

The following is an output of a goroutine profile on an application that's been running for a few hours, showing 9899 goroutines for the TCP handler function, despite the application only actually having a handful of active connections open
![ipfix-goroutines](https://user-images.githubusercontent.com/20494388/107891977-0e890800-6ef0-11eb-829f-9db49f91343f.png)

**Expected behavior**
After a TCP connection is closed (basically after any of the break conditions in https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L69-L95), all goroutines specific to that client connection should be closed

**Actual Behavior**
After a TCP connection is closed, [the goroutine](https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L65) reading from the connection is closed by one of the break statements, however https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L98 waits forever on the clients errChan, which doesn't have any value sent to it, so the function never gets past that step, and the goroutine lives forever.

**Versions**
First noticed while on v0.4.2, bumped to v0.4.4 and still see the issue

**Additional context**
I'm running the collector(s) behind a load balancer, while performs health checks by way of a simple TCP handshake to make sure that the application is up and listening. These health checks occur often enough that in the span of a single day, about 500MB of memory is taken up by the unclosed goroutines

From my initial glance, it looks like perhaps a value should be passed to the errChan right before any of the break statements, or just [after the infinite for loop](https://github.com/vmware/go-ipfix/blob/master/pkg/collector/tcp.go#L96). With that, the CollectingProcess.closeAllClients would still work, but clients which have had their connection closed will be immediately deleted

**Comment by sheacloud** [comment]
I see this is in fact resolved in v0.4.4 via https://github.com/vmware/go-ipfix/commit/cc5742ac64603bad26d956bd34ff8abf3c06d476, I hadn't successfully updated the code to v0.4.4 so it was still actually running v0.4.2 with the issue, and was only looking at the master branch. Closing this out.

**Comment by srikartati** [comment]
Thanks @sheacloud for analyzing with pprof. Please let us if you see any more performance issues in the code.
