### ISSUE TITLE
More performance fixes in the code

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#209]
As part of benchmark tests in Antrea, we found several performance bottlenecks. We already fixed some. There are some more. Listing those here, so that we could track and work on those.

- [x] Pre-allocate memory for bytes in encoding records. Not required for decoding records.
- [x] Move from `bytes.Buffer` to `bytes` in decoded and encoded set.
- [x] Optimize buffer management when processing messages in collector process.
- [x] Need to revisit the requirement for structure `NewInfoElementWithValue`
- [x] Casting to interface is costly. Avoid this when decoding.

@zyiou Please feel free to add more bottlenecks to this list.

**Comment by srikartati** [comment]
Buffer management handled here in collector process: https://github.com/vmware/go-ipfix/pull/213

**Comment by zyiou** [comment]
Moving from `bytes.Buffer` to `bytes` for set and message, and pre-allocate memory for encoding records are handled by #215

**Comment by srikartati** [comment]
With performance tests, we found that casting to `interface` while decoding is very costly. Because of this we are allocating a lot of objects with big sizes. This can lead to memory fragmentation.

Please note that `DecodeBytesToIEDataType` is modified version of `DecodeToIEDataType` which takes in bytes directly but returns the `interface`. While returning, we cast the decoded value back to interface. This is costly and can lead to a lot of allocations. Figure out a way to store the value without returning. 

One solution in my mind is to allocate different objects for different data types.

```
(pprof) top
Showing nodes accounting for 314179179, 70.43% of 446097898 total
Dropped 360 nodes (cum <= 2230489)
Showing top 10 nodes out of 86
      flat  flat%   sum%        cum   cum%
 115034469 25.79% 25.79%  115034469 25.79%  github.com/vmware/go-ipfix/pkg/entities.DecodeBytesToIEDataType
  76967129 17.25% 43.04%   76967129 17.25%  github.com/vmware/go-ipfix/pkg/intermediate.(*AggregationProcess).addFieldsForStatsAggregation
  25063203  5.62% 48.66%   25063203  5.62%  k8s.io/klog/v2.(*loggingT).header
  17186617  3.85% 52.51%   17186617  3.85%  github.com/vmware/go-ipfix/pkg/entities.NewDataRecord (inline)
  15576148  3.49% 56.00%  132052532 29.60%  github.com/vmware/go-ipfix/pkg/intermediate.(*worker).start.func1
  14680288  3.29% 59.29%   14680288  3.29%  reflect.copyVal
  13861074  3.11% 62.40%   13861074  3.11%  net.IP.String
  12307972  2.76% 65.16%  208298636 46.69%  github.com/vmware/go-ipfix/pkg/collector.(*CollectingProcess).handleTCPClient.func1
  11836338  2.65% 67.81%   11836338  2.65%  github.com/vmware/go-ipfix/pkg/entities.NewMessage (inline)
  11665941  2.62% 70.43%   11665941  2.62%  bytes.NewBuffer (inline
```

**Comment by srikartati** [comment]
All identified performance fixes are merged. Closing this issue.
