### ISSUE TITLE
Implement IPFIX mediator as per RFC7119

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#3]
Following the RFC below, we need to implement IPFIX mediator like IPFIX exporter.
https://tools.ietf.org/html/rfc7119

This will be needed if we want to build IPFIX based flow aggregator to aggregate/enhance flow records and send them to an IPFIX collector.

**Comment by srikartati** [comment]
We need implementation of the collector process and the intermediate process. Exporting process is already available.

**Comment by zyiou** [comment]
Collecting Process is available from [PR#13](#13). We still need to implement intermediate process.
