### ISSUE TITLE
Antrea IPFIX registry: Create a sub-assignment under VMware enterprise registry or apply for new one 

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#36]
More context here: https://github.com/vmware-tanzu/antrea/pull/1280#discussion_r493978397

**Comment by robcowart** [comment]
PEN 55829 is already assigned.
https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers

Requesting a PEN for Antrea is super easy. Just fill out this form... https://pen.iana.org/pen/PenApplication.page
You may first get an email to confirm the details provided, and will get an email to accept the assignment a few days later. That is all there is to it.

**Comment by srikartati** [comment]
> PEN 55829 is already assigned.
> https://www.iana.org/assignments/enterprise-numbers/enterprise-numbers
> 
> Requesting a PEN for Antrea is super easy. Just fill out this form... https://pen.iana.org/pen/PenApplication.page
> You may first get an email to confirm the details provided, and will get an email to accept the assignment a few days later. That is all there is to it.

Thanks Rob for the info. I contacted blow person to see if Antrea specific fields can be added to VMware enterprise ID or for any suggestion as he is the contact person for VMware inc.

6876

VMware Inc.

Michael MacFaden

mrm&vmware.com

I will wait for response for a couple of days. Regardless, I also feel we should apply for a new enterprise ID for Antrea.

**Comment by srikartati** [comment]
Got a new PEN number. https://github.com/vmware-tanzu/antrea/issues/1448
Closing this issue.
