### ISSUE TITLE
Get templateID from set instead of record

### ISSUE THREAD

**Issue by zyiou** [vmware/go-ipfix#79]
We should move `GetTemplateID` function from record to set since all records under the same set will have same template

**Comment by srikartati** [comment]
Thanks for the issue. 
Above seems to be true for Data set but not for template set. Seems like the template set could have multiple template records with different template IDs? https://tools.ietf.org/html/rfc7011#section-3.4

**Comment by zyiou** [comment]
Closed since it is not necessary now and the reason provided by @srikartati above.
