### ISSUE TITLE
"Upload assets to release" github CI workflow not working

### ISSUE THREAD

**Issue by srikartati** [vmware/go-ipfix#87]
This workflow is supposed to compile the binary of standalone collector and add it to released assets when we create a new release in go-ipfix repo. 
It works properly on the fork for test releases.

Currently, released assets are not used anywhere, but this may change in the future.

**Comment by zyiou** [comment]
Closed since `upload assets to release` works well in [v0.4.0 release](https://github.com/vmware/go-ipfix/actions?query=workflow%3A%22Upload+assets+to+release%22).
